### PR TITLE
Quick design pass

### PR DESCRIPTION
**Pull request by lydiascarf**
I just wanted to get some of the easy tweaks through to make it look a bit more like the old site. Here's what it looks like:

Screenshot 2023-09-05 at 2 44 46 PM
Screenshot 2023-09-05 at 2 46 18 PM
Screenshot 2023-09-05 at 2 46 25 PM

### CODE REVIEW

**Comment by BryanQuigley** [comment]
It's amazing how much better it looks just with the bg color change.  

Everything looks great so far - my only question is why choose a new font?

**Comment by BryanQuigley** [comment]
Opened an [issue](https://github.com/azavea/opendataphilly-jkan/issues/88) while thinking about it (and it doesn't have to be done here) - but it might be nice to have a button at the top right to get to GitHub.

**Comment by lydiascarf** [comment]
> It's amazing how much better it looks just with the bg color change.
> 
> Everything looks great so far - my only question is why choose a new font?

Thanks!! The font change was to match the old design (see [here](https://github.com/azavea/opendataphilly-jkan/issues/35#issuecomment-1688430538))

**Review by BryanQuigley — APPROVED** [review]
Looks great.  I'm still not getting fonts. 

Removing both of these lines, really had minimal impact on the look.
-  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Lato">
-  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

They are slightly different, but I don't see an advantage either way.

**Comment by lydiascarf** [comment]
@BryanQuigley it's most visible in the header links I think, but it's not drastic

**Pull request merged**
